#version: "3.9"

services:
  dservice:
    build:
      context: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-5432}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - dservice
    ports:
      - 8000:8000
